### PR TITLE
Rebuild to update toolchain

### LINKED ISSUE #8: @conda-forge-admin, please add user @zklaus
### Additional comment:

This library is part of the dependency graph of subversion and I'd like to help update and port it to arm64.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #8.

This repo needs a bit of TLC to come up to speed. That should be the foundation to include the outstanding version updates and pave the way to bring subversion to arm64.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@mariusvniekerk, could you please have a look? This is the first step towards bringing subversion to arm64. If you agree, I will next take care of version updates here, then migrate to arm64 and then move on to the rest of the deps.

**Comment by zklaus** [comment]
@conda-forge/core, I'd like to move the migration of subversion to arm64 forward. Could you have a look?

**Comment by hmaarrfk** [comment]
you don't want to update the version too? it looks quite old. But it seems you want to start with this, then update the version later?

**Comment by zklaus** [comment]
@hmaarrfk that's exactly my thinking. Since there are a number of versions outstanding, I wanted to try to successively build those to give us options.

**Pull request merged**
